CWNew/force-app/main/default/objects/CW_Route__c/CW_Route__c.object-meta.xml
<CustomObject>
    <description>Determines in which route the vehicle runs</description>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Route Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>CW_Departure_Time__c</fullName>
    <description>Stores Departure Time</description>
    <label>Departure Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Destination__c.field-meta.xml
<CustomField>
    <fullName>CW_Destination__c</fullName>
    <description>Stores the destination of the route</description>
    <label>To</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Cochin</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Warangal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Origin__c.field-meta.xml
<CustomField>
    <fullName>CW_Origin__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Cochin</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Warangal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Runs_On__c.field-meta.xml
<CustomField>
    <fullName>CW_Runs_On__c</fullName>
    <label>Runs On</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Trip_Duration__c.field-meta.xml
<CustomField>
    <fullName>CW_Trip_Duration__c</fullName>
    <description>Enter in HH:MM format</description>
    <inlineHelpText>Enter in HH:MM format</inlineHelpText>
    <label>Trip Duration</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle__c</fullName>
    <description>Stores which vehicle is used for the route</description>
    <label>Vehicle</label>
    <referenceTo>CW_Vehicle__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/CW_Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>T-{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Triip Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Arrival__c.field-meta.xml
<CustomField>
    <fullName>CW_Arrival__c</fullName>
    <description>Stores arrival time</description>
    <label>Arrival</label>
    <type>DateTime</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Departure__c.field-meta.xml
<CustomField>
    <fullName>CW_Departure__c</fullName>
    <description>Stores departure date and time</description>
    <label>Departure</label>
    <type>DateTime</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Is_Booking_Closed__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Booking_Closed__c</fullName>
    <formula>CW_Departure__c &lt; NOW()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Booking Closed</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Is_Seats_Available__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Seats_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Seats Available</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Layout_JSON__c.field-meta.xml
<CustomField>
    <fullName>CW_Layout_JSON__c</fullName>
    <label>Layout JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Price__c.field-meta.xml
<CustomField>
    <fullName>CW_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Route__c.field-meta.xml
<CustomField>
    <fullName>CW_Route__c</fullName>
    <label>Route</label>
    <referenceTo>CW_Route__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Travel_Date__c.field-meta.xml
<CustomField>
    <fullName>CW_Travel_Date__c</fullName>
    <formula>DATEVALUE( CW_Departure__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Travel Date</label>
    <type>Date</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle__c/CW_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Vehicle__c/fields/CW_Vehicle_Layout__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle_Layout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Layout</label>
    <referenceTo>CW_Vehicle_Layout__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle_Layout__c/CW_Vehicle_Layout__c.object-meta.xml
<CustomObject>
    <label>Vehicle Layout</label>
    <nameField>
        <label>Vehicle Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/classes/CW_SOQLHelper.cls
/*
@Name : CW_SOQLHelper
@Author : Varun Kumar Sirisilla
@Description : All the SOQL queries are performed in this class
*/ 
public with sharing class CW_SOQLHelper {
    
    /*
@Name : getActiveRoutesQuery
@Author : Varun Kumar Sirisilla
@Description : This method will get all active routes record and passed to batch class
@return : String
*/ 
    public static String getActiveRoutesQuery() {
        return 'SELECT Id, CW_Vehicle__r.CW_Vehicle_Layout__r.CW_Layout_JSON__c, CW_Departure_Time__c, CW_Price__c, CW_Runs_On__c, CW_Trip_Duration__c ' +
            'FROM CW_Route__c ' +
            'WHERE CW_Is_Active__c = true WITH USER_MODE';
    }
    
    /*
@Name : getMatchingTrips
@Author : Varun Kumar Sirisilla
@Description : This method get the trip records based on origin and destination and travel date
@params : String, String, Date
@return : List<CW_Trip__c>
*/ 
    public static List<CW_Trip__c> getMatchingTrips(String origin, String destination, Date travelDate) {
        return [SELECT Id, CW_Layout_JSON__c, CW_Price__c, CW_Arrival__c, CW_Departure__c, 
                CW_Route__r.CW_Origin__c, CW_Route__r.CW_Destination__c  
                FROM CW_Trip__c 
                WHERE CW_Route__r.CW_Destination__c = :destination 
                AND CW_Route__r.CW_Origin__c = :origin 
                AND CW_Travel_Date__c = :travelDate 
                AND CW_Is_Active__c = TRUE 
                AND CW_Is_Seats_Available__c = TRUE 
                AND CW_Is_Booking_Closed__c  = FALSE 
                WITH USER_MODE];
    }
    
    /*
@Name : getExistingTripRec
@Author : Varun Kumar Sirisilla
@Description : This method get the trip records
@params : Id
@return : CW_Trip__c
*/ 
    public static CW_Trip__c getExistingTripRec(Id tripId) {
        return [SELECT Id, CW_Layout_JSON__c  
                FROM CW_Trip__c 
                WHERE Id = :tripId WITH USER_MODE];
    }
    
}