CWNew/force-app/main/default/objects/CW_Route__c/CW_Route__c.object-meta.xml
<CustomObject>
    <description>Determines in which route the vehicle runs</description>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Route Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>CW_Departure_Time__c</fullName>
    <description>Stores Departure Time</description>
    <label>Departure Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Destination__c.field-meta.xml
<CustomField>
    <fullName>CW_Destination__c</fullName>
    <description>Stores the destination of the route</description>
    <label>To</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Cochin</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Warangal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Origin__c.field-meta.xml
<CustomField>
    <fullName>CW_Origin__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Cochin</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Warangal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Runs_On__c.field-meta.xml
<CustomField>
    <fullName>CW_Runs_On__c</fullName>
    <label>Runs On</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Trip_Duration__c.field-meta.xml
<CustomField>
    <fullName>CW_Trip_Duration__c</fullName>
    <description>Enter in HH:MM format</description>
    <inlineHelpText>Enter in HH:MM format</inlineHelpText>
    <label>Trip Duration</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle__c</fullName>
    <description>Stores which vehicle is used for the route</description>
    <label>Vehicle</label>
    <referenceTo>CW_Vehicle__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle__c/CW_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Vehicle__c/fields/CW_Maker__c.field-meta.xml
<CustomField>
    <fullName>CW_Maker__c</fullName>
    <description>Select maker of the vehicle</description>
    <label>Maker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tata Motors</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle__c/fields/CW_Vehicle_Layout__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle_Layout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Layout</label>
    <referenceTo>CW_Vehicle_Layout__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle__c/fields/CW_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle_Type__c</fullName>
    <description>Select Vehicle Type</description>
    <label>Vehicle Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle_Layout__c/CW_Vehicle_Layout__c.object-meta.xml
<CustomObject>
    <label>Vehicle Layout</label>
    <nameField>
        <label>Vehicle Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/classes/CW_TripTriggerHandlerTest.cls
/*
@Name : CW_TripTriggerHandlerTest
@Author : Varun Kumar Sirisilla
@Description : test class for CW_TripTriggerHandler
*/
@isTest
private class CW_TripTriggerHandlerTest {
    
    /**
     * Test method to validate trip overlap detection.
     */
    @isTest
    static void testTripOverlapDetection() {
        // Create test vehicle layout
        CW_Vehicle_Layout__c layout = new CW_Vehicle_Layout__c();
        layout.Name = 'Test Layout';
        layout.CW_Layout_JSON__c  = '{"rows":[{"rowNo":1,"seats":[{"seatNoLabel":"A","seatNoValue":"1-A","isSelected":false,"isAvailable":true,"class":"seatButtonAvailableStyle slds-button slds-button_neutral slds-button_stretch"},{"seatNoLabel":"B","seatNoValue":"1-B","isSelected":false,"isAvailable":true,"class":"seatButtonAvailableStyle slds-button slds-button_neutral slds-button_stretch"}]}]}';
        insert layout;
        
        // Create test vehicle
        CW_Vehicle__c testVehicle = new CW_Vehicle__c();
        testVehicle.CW_Vehicle_Layout__c  = layout.Id;
        testVehicle.CW_Maker__c = 'Tata Motors';
        testVehicle.CW_Vehicle_Type__c = 'Bus';
        insert testVehicle;
        
        // Create test routes
        CW_Route__c route = new CW_Route__c();
        route.CW_Origin__c = 'Hyderabad';
        route.CW_Destination__c = 'Chennai';
        route.CW_Price__c = 1000;
        route.CW_Is_Active__c = TRUE;
        route.CW_Departure_Time__c = Time.newInstance(14, 30, 0, 0);
        route.CW_Trip_Duration__c = '12:40';
        route.CW_Vehicle__c = testVehicle.Id;
        route.CW_Runs_On__c = 'Sunday;Tuesday;Wednesday;Thursday;Friday;Saturday';
        insert route;
        
        CW_Route__c route1 = new CW_Route__c();
        route1.CW_Origin__c = 'Hyderabad';
        route1.CW_Destination__c = 'Cochin';
        route1.CW_Price__c = 1000;
        route1.CW_Is_Active__c = TRUE;
        route1.CW_Departure_Time__c = Time.newInstance(14, 30, 0, 0);
        route1.CW_Trip_Duration__c = '12:40';
        route1.CW_Vehicle__c = testVehicle.Id;
        route1.CW_Runs_On__c = 'Sunday;Tuesday;Wednesday;Thursday;Friday;Saturday';
        insert route1;
        
        // Retrieve inserted route records
        CW_Route__c routeRecord = [SELECT Id, 
                                   CW_Vehicle__r.CW_Vehicle_Layout__r.CW_Layout_JSON__c, 
                                   CW_Departure_Time__c, 
                                   CW_Price__c, 
                                   CW_Runs_On__c, 
                                   CW_Trip_Duration__c FROM CW_Route__c WHERE Id =: route.Id];
        
        CW_Route__c routeRecord1 = [SELECT Id, 
                                    CW_Vehicle__r.CW_Vehicle_Layout__r.CW_Layout_JSON__c, 
                                    CW_Departure_Time__c, 
                                    CW_Price__c, 
                                    CW_Runs_On__c, 
                                    CW_Trip_Duration__c FROM CW_Route__c WHERE Id =: route1.Id];
        
        // Create flow inputs for trip creation
        List<CW_CreateTripRecordsBatch.FlowOutputs> flowOutputs = new List<CW_CreateTripRecordsBatch.FlowOutputs>();
        CW_CreateTripRecordsBatch.FlowInputs input = new CW_CreateTripRecordsBatch.FlowInputs();
        
        // Test trip creation for the first route
        input.route = routeRecord;
        input.travelDate = Date.today().addDays(49);
        input.layoutJSON = routeRecord.CW_Vehicle__r.CW_Vehicle_Layout__r.CW_Layout_JSON__c;
        flowOutputs = CW_CreateTripRecordsBatch.createTrip(new List<CW_CreateTripRecordsBatch.FlowInputs>{input});
        // Assert that the trip creation is successful
        System.assertEquals('Trip Record Created Successfully!', flowOutputs[0].result);
        
        // Test trip creation for the second route
        input.route = routeRecord1;
        input.travelDate = Date.today().addDays(49);
        input.layoutJSON = routeRecord1.CW_Vehicle__r.CW_Vehicle_Layout__r.CW_Layout_JSON__c;
        flowOutputs = CW_CreateTripRecordsBatch.createTrip(new List<CW_CreateTripRecordsBatch.FlowInputs>{input});
        // Assert that the trip creation is unsuccessful due to trip overlap
        System.assertEquals(true, flowOutputs[0].result != 'Trip Record Created Successfully!');
    }
}