CWNew/force-app/main/default/objects/CW_General_Setting__mdt/CW_General_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Stores all the general Setting</description>
    <label>General Setting</label>
    <pluralLabel>General Settings</pluralLabel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_General_Setting__mdt/fields/CW_Value__c.field-meta.xml
<CustomField>
    <fullName>CW_Value__c</fullName>
    <description>Stores the settings value</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/CW_Route__c.object-meta.xml
<CustomObject>
    <description>Determines in which route the vehicle runs</description>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Route Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>CW_Departure_Time__c</fullName>
    <description>Stores Departure Time</description>
    <label>Departure Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Runs_On__c.field-meta.xml
<CustomField>
    <fullName>CW_Runs_On__c</fullName>
    <label>Runs On</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Trip_Duration__c.field-meta.xml
<CustomField>
    <fullName>CW_Trip_Duration__c</fullName>
    <description>Enter in HH:MM format</description>
    <inlineHelpText>Enter in HH:MM format</inlineHelpText>
    <label>Trip Duration</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle__c</fullName>
    <description>Stores which vehicle is used for the route</description>
    <label>Vehicle</label>
    <referenceTo>CW_Vehicle__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/CW_Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>T-{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Triip Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Arrival__c.field-meta.xml
<CustomField>
    <fullName>CW_Arrival__c</fullName>
    <description>Stores arrival time</description>
    <label>Arrival</label>
    <type>DateTime</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Departure__c.field-meta.xml
<CustomField>
    <fullName>CW_Departure__c</fullName>
    <description>Stores departure date and time</description>
    <label>Departure</label>
    <type>DateTime</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Is_Seats_Available__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Seats_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Seats Available</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Layout_JSON__c.field-meta.xml
<CustomField>
    <fullName>CW_Layout_JSON__c</fullName>
    <label>Layout JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Price__c.field-meta.xml
<CustomField>
    <fullName>CW_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Route__c.field-meta.xml
<CustomField>
    <fullName>CW_Route__c</fullName>
    <label>Route</label>
    <referenceTo>CW_Route__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle__c/CW_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Vehicle__c/fields/CW_Vehicle_Layout__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle_Layout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Layout</label>
    <referenceTo>CW_Vehicle_Layout__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle_Layout__c/CW_Vehicle_Layout__c.object-meta.xml
<CustomObject>
    <label>Vehicle Layout</label>
    <nameField>
        <label>Vehicle Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/classes/CW_CreateTripRecordsBatch.cls
/*
@Name : CW_CreateTripRecordsBatch
@Author : Varun Kumar Sirisilla
@Description : Batch class which will create trip records on daily basis
*/ 
public with sharing class CW_CreateTripRecordsBatch implements Database.Batchable<sObject>, Schedulable  {
    
    private Map<String, CW_General_Setting__mdt> cwGeneralSettings = CW_General_Setting__mdt.getAll();
    
    /*
@Name : start
@Author : Varun Kumar Sirisilla
@Description : Start method-> returns active routes
*/ 
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(CW_SOQLHelper.getActiveRoutesQuery());
    }
    
    /*
@Name : execute
@Author : Varun Kumar Sirisilla
@Description : Includes trip record creation logic
*/ 
    public void execute(Database.BatchableContext BC, List<CW_Route__c> scope) {
        List<CW_Trip__c> tripInsertRecords = new List<CW_Trip__c>();
        
        for (CW_Route__c route : scope) {
            CW_Trip__c tripRec = new CW_Trip__c();
            
            populateArrAndDepDtTime(tripRec,route,Date.today().addDays(Integer.valueOf(cwGeneralSettings.get('CW_Booking_Opens_Before').CW_Value__c)));
            
            String dayOfWeek = tripRec.CW_Departure__c.format('EEEE');
            
            if (route.CW_Runs_On__c.contains(dayOfWeek)) {
                populateTripRecord(tripRec,route);
                tripInsertRecords.add(tripRec);
            }
        }
        Database.SaveResult[] saveResults = Database.insert(tripInsertRecords, false);
        //Logging errored record to log object will be covered in next phase
        for (Database.SaveResult saveResult : saveResults) {
            if (saveResult.isSuccess()) {
                System.debug('Record Succesffully created '+saveResult.getId());
            } else {
                // Record failed to insert/update
                for (Database.Error error : saveResult.getErrors()) {
                    System.debug('Record Failed'+error);
                }
            }
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        // Optional: Add any finish logic here
    }
    
    /*
@Name : execute
@Author : Varun Kumar Sirisilla
@Description : schedules CW_CreateTripRecordsBatch
*/ 
    public void execute(SchedulableContext sc) {
        CW_CreateTripRecordsBatch batchJob = new CW_CreateTripRecordsBatch(); 
        Database.executeBatch(batchJob,Integer.valueOf(cwGeneralSettings.get('CW_Trip_Creation_Batch_Size').CW_Value__c));            
    }
    
    /*
@Name : populateArrAndDepDtTime
@Author : Varun Kumar Sirisilla
@Description : calculate arrival and departure date time
*/ 
    public static void populateArrAndDepDtTime(CW_Trip__c tripRec,CW_Route__c route,Date travelDate){
        List<String> tripDurationFormat = route.CW_Trip_Duration__c.split(':');
        Datetime departureDateTime = Datetime.newInstance(
            travelDate,
            route.CW_Departure_Time__c
        );
        Datetime arrivalDateTime = departureDateTime.addHours(Integer.valueOf(tripDurationFormat[0]))
            .addMinutes(Integer.valueOf(tripDurationFormat[1]));
        tripRec.CW_Departure__c = departureDateTime;
        tripRec.CW_Arrival__c = arrivalDateTime;
    }
    
    /*
@Name : createTrip
@Author : Varun Kumar Sirisilla
@Description : calls from screen flow to create trip record
*/ 
    @InvocableMethod
    public static List<FlowOutputs> createTrip(List<FlowInputs> inputList){
        List<FlowOutputs> flowOutputLst = new List<FlowOutputs>();
        FlowOutputs flowOutput = new FlowOutputs();
        try{
            FlowInputs input = inputList[0];
            CW_Route__c route = input.route;
            CW_Trip__c tripRec = new CW_Trip__c();
            populateTripRecord(tripRec,route);
            populateArrAndDepDtTime(tripRec,route,input.travelDate);
            tripRec.CW_Layout_JSON__c = input.layoutJSON;
            insert tripRec;
            flowOutput.result = 'Trip Record Created Successfully!';
            flowOutputLst.add(flowOutput);
            return flowOutputLst;
        }catch(Exception e){
            flowOutput.result = e.getMessage();
            flowOutputLst.add(flowOutput);
            return flowOutputLst;
        }
    }
    
    /**
* Inner class to represent the output of the invocable method.
*/
    public class FlowOutputs{
        @InvocableVariable(required = true)
        public String result;
    }
    
    /**
* Inner class to represent the input variables for the invocable method.
*/
    public class FlowInputs {
        @InvocableVariable(required = true)
        public CW_Route__c route;
        
        @InvocableVariable(required = true)
        public Date travelDate;
        
        @InvocableVariable(required = true)
        public String layoutJSON;
        
    }
    
    /**
* Populates trip record fields based on the provided route information.
* 
* @param tripRec The trip record to populate.
* @param route The route information to use for populating the trip record.
*/
    private static void populateTripRecord(CW_Trip__c tripRec,CW_Route__c route){
        tripRec.CW_Route__c = route.Id;
        tripRec.CW_Is_Active__c = TRUE;
        tripRec.CW_Is_Seats_Available__c = TRUE;
        tripRec.CW_Price__c  = route.CW_Price__c;
        tripRec.CW_Layout_JSON__c  = route.CW_Vehicle__r.CW_Vehicle_Layout__r.CW_Layout_JSON__c;
    }
    
}