CWNew/force-app/main/default/objects/CW_Passenger__c/CW_Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Passenger__c/fields/CW_Age__c.field-meta.xml
<CustomField>
    <fullName>CW_Age__c</fullName>
    <label>Age</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Passenger__c/fields/CW_Gender__c.field-meta.xml
<CustomField>
    <fullName>CW_Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Passenger__c/fields/CW_Reservation__c.field-meta.xml
<CustomField>
    <fullName>CW_Reservation__c</fullName>
    <label>Reservation</label>
    <referenceTo>CW_Reservation__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Passenger__c/fields/CW_Seat_Number__c.field-meta.xml
<CustomField>
    <fullName>CW_Seat_Number__c</fullName>
    <label>Seat Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Reservation__c/CW_Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Reservation__c/fields/CW_Address__c.field-meta.xml
<CustomField>
    <fullName>CW_Address__c</fullName>
    <label>Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Reservation__c/fields/CW_Phone__c.field-meta.xml
<CustomField>
    <fullName>CW_Phone__c</fullName>
    <label>Phone</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Reservation__c/fields/CW_Seat_Numbers__c.field-meta.xml
<CustomField>
    <fullName>CW_Seat_Numbers__c</fullName>
    <label>Seat Numbers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Reservation__c/fields/CW_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>CW_Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Reservation__c/fields/CW_Trip__c.field-meta.xml
<CustomField>
    <fullName>CW_Trip__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trip</label>
    <referenceTo>CW_Trip__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/CW_Route__c.object-meta.xml
<CustomObject>
    <description>Determines in which route the vehicle runs</description>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Route Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>CW_Departure_Time__c</fullName>
    <description>Stores Departure Time</description>
    <label>Departure Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Destination__c.field-meta.xml
<CustomField>
    <fullName>CW_Destination__c</fullName>
    <description>Stores the destination of the route</description>
    <label>To</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Cochin</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Warangal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Origin__c.field-meta.xml
<CustomField>
    <fullName>CW_Origin__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Cochin</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Warangal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Runs_On__c.field-meta.xml
<CustomField>
    <fullName>CW_Runs_On__c</fullName>
    <label>Runs On</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Trip_Duration__c.field-meta.xml
<CustomField>
    <fullName>CW_Trip_Duration__c</fullName>
    <description>Enter in HH:MM format</description>
    <inlineHelpText>Enter in HH:MM format</inlineHelpText>
    <label>Trip Duration</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Route__c/fields/CW_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle__c</fullName>
    <description>Stores which vehicle is used for the route</description>
    <label>Vehicle</label>
    <referenceTo>CW_Vehicle__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/CW_Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>T-{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Triip Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CW_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Layout_JSON__c.field-meta.xml
<CustomField>
    <fullName>CW_Layout_JSON__c</fullName>
    <label>Layout JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Price__c.field-meta.xml
<CustomField>
    <fullName>CW_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Trip__c/fields/CW_Route__c.field-meta.xml
<CustomField>
    <fullName>CW_Route__c</fullName>
    <label>Route</label>
    <referenceTo>CW_Route__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle__c/CW_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/objects/CW_Vehicle__c/fields/CW_Maker__c.field-meta.xml
<CustomField>
    <fullName>CW_Maker__c</fullName>
    <description>Select maker of the vehicle</description>
    <label>Maker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tata Motors</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle__c/fields/CW_Vehicle_Layout__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle_Layout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Layout</label>
    <referenceTo>CW_Vehicle_Layout__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle__c/fields/CW_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>CW_Vehicle_Type__c</fullName>
    <description>Select Vehicle Type</description>
    <label>Vehicle Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CWNew/force-app/main/default/objects/CW_Vehicle_Layout__c/CW_Vehicle_Layout__c.object-meta.xml
<CustomObject>
    <label>Vehicle Layout</label>
    <nameField>
        <label>Vehicle Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CWNew/force-app/main/default/classes/CW_BookVehicleControllerTest.cls
/*
@Name : CW_BookVehicleControllerTest
@Author : Varun Kumar Sirisilla
@Description : test class for CW_BookVehicleController
*/
@isTest
public class CW_BookVehicleControllerTest {
    
    /*
@Name : createTestData
@Author : Varun Kumar Sirisilla
@Description : Creates test data
*/
    @TestSetup static void createTestData() {
        CW_Vehicle_Layout__c layout = new CW_Vehicle_Layout__c();
        layout.Name = 'Test Layout';
        layout.CW_Layout_JSON__c  = '{"rows":[{"rowNo":1,"seats":[{"seatNoLabel":"A","seatNoValue":"1-A","isSelected":false,"isAvailable":true,"class":"seatButtonAvailableStyle slds-button slds-button_neutral slds-button_stretch"},{"seatNoLabel":"B","seatNoValue":"1-B","isSelected":false,"isAvailable":true,"class":"seatButtonAvailableStyle slds-button slds-button_neutral slds-button_stretch"}]}]}';
        insert layout;
        
        CW_Vehicle__c testVehicle = new CW_Vehicle__c();
        testVehicle.CW_Vehicle_Layout__c  = layout.Id;
        testVehicle.CW_Maker__c = 'Tata Motors';
        testVehicle.CW_Vehicle_Type__c = 'Bus';
        insert testVehicle;
        
        CW_Route__c route = new CW_Route__c();
        route.CW_Origin__c = 'Hyderabad';
        route.CW_Destination__c = 'Chennai';
        route.CW_Price__c = 1000;
        route.CW_Is_Active__c = TRUE;
        route.CW_Departure_Time__c = Time.newInstance(14, 30, 0, 0);
        route.CW_Trip_Duration__c = '12:40';
        route.CW_Vehicle__c = testVehicle.Id;
        route.CW_Runs_On__c = 'Sunday;Monday;Tuesday;Wednesday;Thursday;Friday;Saturday';
        insert route;
        
        CW_Route__c route1 = new CW_Route__c();
        route1.CW_Origin__c = 'Hyderabad';
        route1.CW_Destination__c = 'Cochin';
        route1.CW_Price__c = 1000;
        route1.CW_Is_Active__c = TRUE;
        route1.CW_Departure_Time__c = Time.newInstance(14, 30, 0, 0);
        route1.CW_Trip_Duration__c = '12:40';
        route1.CW_Vehicle__c = testVehicle.Id;
        route1.CW_Runs_On__c = 'Sunday;Monday;Tuesday;Wednesday;Thursday;Friday;Saturday';
        insert route1;
        
        CW_Route__c routeRecord = [SELECT Id, 
                                   CW_Vehicle__r.CW_Vehicle_Layout__r.CW_Layout_JSON__c, 
                                   CW_Departure_Time__c, 
                                   CW_Price__c, 
                                   CW_Runs_On__c, 
                                   CW_Trip_Duration__c FROM CW_Route__c WHERE Id =: route.Id];
        
        CW_CreateTripRecordsBatch.FlowInputs input = new CW_CreateTripRecordsBatch.FlowInputs();
        input.route = routeRecord;
        input.travelDate = Date.today().addDays(49);
        input.layoutJSON = routeRecord.CW_Vehicle__r.CW_Vehicle_Layout__r.CW_Layout_JSON__c;
        CW_CreateTripRecordsBatch.createTrip(new List<CW_CreateTripRecordsBatch.FlowInputs>{input});
    }
    
    /*
@Name : testCreateTripsBatch
@Author : Varun Kumar Sirisilla
@Description : tests CreateTripsBatch class
*/
    @isTest
    static void testCreateTripsBatch(){
        Test.startTest();
        String cronExp = '0 0 0 * * ?'; // Example: Daily at midnight
        String jobId = System.schedule('TESTING_CW_Create_Trips_Batch',cronExp, new CW_CreateTripRecordsBatch());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(cronExp,ct.CronExpression);
        Test.stopTest();
    }
    
    /*
@Name : testGetMatchingTrips
@Author : Varun Kumar Sirisilla
@Description : this will get test GetMatchingTrips methods
*/
    @isTest
    static void testGetMatchingTrips(){
        List<CW_Trip__c> tripRecords = CW_BookVehicleController.getMatchingTrips('Hyderabad','Chennai',Date.today().addDays(49));
        System.assertEquals(TRUE,tripRecords.size() > 0);
    }
    
    /*
@Name : testBookSeats
@Author : Varun Kumar Sirisilla
@Description : this will get test BookSeats method
*/
    @isTest
    static void testBookSeats(){
        CW_Reservation__c reservation = new CW_Reservation__c();
        reservation.CW_Address__c = 'Test';
        reservation.CW_Seat_Numbers__c = '1-A';
        reservation.CW_Total_Amount__c = 1000;
        reservation.CW_Phone__c = '1323232323';
        reservation.CW_Trip__c = [SELECT Id FROM CW_Trip__c LIMIT 1].Id;
        CW_Passenger__c passenger = new CW_Passenger__c();
        passenger.Name = 'Test';
        passenger.CW_Gender__c = 'Male';
        passenger.CW_Age__c = 28;
        passenger.CW_Seat_Number__c = '1-A';
        String resultPos = CW_BookVehicleController.bookSeats(JSON.serialize(new List<CW_Passenger__c>{passenger}),JSON.serialize(reservation));
        System.assertEquals(TRUE,resultPos == 'success');
        
        String resultNeg = CW_BookVehicleController.bookSeats(JSON.serialize(new List<CW_Passenger__c>{passenger}),JSON.serialize(reservation));
        System.assertEquals(TRUE,resultNeg == 'Selected Seats Not Available for Booking');
    }
}